In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('student3.csv')
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [5]:
df.shape

(16, 5)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    16 non-null     int64
 1   name    16 non-null     object
 2   class   15 non-null     object
 3   marks   14 non-null     float64
 4   age     14 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 772.0+ bytes

In [7]:
# fix structural errors

In [8]:
df['name']

0        Anil
1        Amit
2      Aniket
3     Ajinkya
4        Asha
5      Ayesha
6        Amar
7       Amita
8        Amol
9        Amol
10      Anmol
11     Surbhi
12      Sujay
13    Subhash
14     Sachin
15    Shalini
Name: name, dtype: object

In [9]:
df['name'] = df['name'].str.title()

In [10]:
df

    roll     name class  marks    age
0      1     Anil    TE   56.77  22.0
1      2     Amit    TE   59.77  21.0
2      3   Aniket    BE   76.88  19.0
3      4  Ajinkya    TE   69.66  20.0
4      5     Asha    TE   63.28   NaN
5      6   Ayesha    BE     NaN  20.0
6      7     Amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     Amol    TE   56.75  20.0
9      9     Amol    TE   56.75  20.0
10    10    Anmol    BE   78.66   NaN
11    11   Surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  Subhash    be   88.45  21.0
14    14   Sachin   NaN   59.33  21.0
15    15  Shalini    TE   63.45  20.0

In [13]:
df['marks ']

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5       NaN
6     65.34
7     68.33
8     56.75
9     56.75
10    78.66
11      NaN
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks , dtype: float64

In [14]:
df['name']

0        Anil
1        Amit
2      Aniket
3     Ajinkya
4        Asha
5      Ayesha
6        Amar
7       Amita
8        Amol
9        Amol
10      Anmol
11     Surbhi
12      Sujay
13    Subhash
14     Sachin
15    Shalini
Name: name, dtype: object

In [17]:
df.columns = df.columns.str.strip()

In [18]:
df['marks']

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5       NaN
6     65.34
7     68.33
8     56.75
9     56.75
10    78.66
11      NaN
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: float64

In [19]:
#duplicate values

In [20]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [21]:
df.duplicated().sum()

np.int64(1)

In [24]:
df.drop_duplicates(inplace=True)
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    be  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [25]:
#missing values

In [26]:
df.count()

roll     15
name     15
class    14
marks    13
age      13
dtype: int64

In [27]:
df.isnull()

     roll   name  class  marks    age
0   False  False  False  False  False
1   False  False  False  False  False
2   False  False  False  False  False
3   False  False  False  False  False
4   False  False  False  False   True
5   False  False  False   True  False
6   False  False  False  False  False
7   False  False  False  False  False
8   False  False  False  False  False
10  False  False  False  False   True
11  False  False  False   True  False
12  False  False  False  False  False
13  False  False  False  False  False
14  False  False   True  False  False
15  False  False  False  False  False

In [28]:
df.isnull().sum()

roll     0
name     0
class    1
marks    2
age      2
dtype: int64

In [29]:
#remove null

In [30]:
df.dropna()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     Amol    TE  56.75  20.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    be  88.45  21.0
15    15  Shalini    TE  63.45  20.0

In [31]:
#filling the mmissing values

In [32]:
df

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28   NaN
5      6   Ayesha    BE    NaN  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66   NaN
11    11   Surbhi    TE    NaN  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    be  88.45  21.0
14    14   Sachin   NaN  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [37]:
df['marks'].fillna(45)

0     56.77
1     59.77
2     76.88
3     69.66
4     63.28
5        45
6     65.34
7     68.33
8     56.75
10    78.66
11       45
12    74.12
13    88.45
14    59.33
15    63.45
Name: marks, dtype: object

In [48]:
df['marks'] = df['marks'].fillna(df['marks'].mean())

In [44]:
df['age'].fillna(df['age'].median())

0     22.0
1     21.0
2     19.0
3     20.0
4     21.0
5     20.0
6     19.0
7     23.0
8     20.0
10    21.0
11    23.0
12    22.0
13    21.0
14    21.0
15    20.0
Name: age, dtype: float64

In [46]:
df['class'].fillna(df['class'].mode())

0      TE
1      TE
2      BE
3      TE
4      TE
5      BE
6      BE
7      be
8      TE
10     BE
11     TE
12     TE
13     be
14    NaN
15     TE
Name: class, dtype: object

In [49]:
df['class'].fillna(df['class'].mode()[0])

0     TE
1     TE
2     BE
3     TE
4     TE
5     BE
6     BE
7     be
8     TE
10    BE
11    TE
12    TE
13    be
14    TE
15    TE
Name: class, dtype: object

In [51]:
df.ffill()

    roll     name class  marks   age
0      1     Anil    TE  56.77  22.0
1      2     Amit    TE  59.77  21.0
2      3   Aniket    BE  76.88  19.0
3      4  Ajinkya    TE  69.66  20.0
4      5     Asha    TE  63.28  20.0
5      6   Ayesha    BE  45.00  20.0
6      7     Amar    BE  65.34  19.0
7      8    Amita    be  68.33  23.0
8      9     Amol    TE  56.75  20.0
10    10    Anmol    BE  78.66  20.0
11    11   Surbhi    TE  45.00  23.0
12    12    Sujay    TE  74.12  22.0
13    13  Subhash    be  88.45  21.0
14    14   Sachin    be  59.33  21.0
15    15  Shalini    TE  63.45  20.0

In [52]:
df.bfill(inplace=True)

In [53]:
df.isnull().sum()

roll     0
name     0
class    0
marks    0
age      0
dtype: int64