In [2]:
import pandas as pd

In [3]:
df3 = pd.read_csv('student3.tsv', sep='\t')
df3

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [4]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [5]:
df3.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [7]:
df3.head(7)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19

In [8]:
df3.head(10)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [9]:
df3.tail()

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [10]:
df3.tail(3)

   roll   name class  marks  age
7     8  amita    BE  68.33   23
8     9   amol    TE  56.75   20
9    10  anmol    BE  78.66   21

In [11]:
df3.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [25]:
df3.iloc[1:4, 0:4]

   roll     name class  marks
1     2     amit    TE  59.77
2     3   aniket    BE  76.88
3     4  ajinkya    TE  69.66

In [24]:
df3.iloc[1:5,[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28

In [26]:
df3.iloc[0::,[0,1,2,4]]

   roll     name class  age
0     1     anil    TE   22
1     2     amit    TE   21
2     3   aniket    BE   19
3     4  ajinkya    TE   20
4     5     asha    TE   20
5     6   ayesha    BE   20
6     7     amar    BE   19
7     8    amita    BE   23
8     9     amol    TE   20
9    10    anmol    BE   21

In [29]:
df3.iloc[5, 1] = "Geet"

In [30]:
df3

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     Geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [38]:
df3.loc[2:5, 'name']

2     aniket
3    ajinkya
4       asha
5       Geet
Name: name, dtype: object

In [39]:
df3.loc[2:5, ['name', 'class']]

      name class
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     Geet    BE

In [41]:
df3.loc[:, 'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       Geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [42]:
df3[['name','class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     Geet    BE
6     amar    BE
7    amita    BE
8     amol    TE
9    anmol    BE

In [45]:
df3['name'].str.upper()

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5       GEET
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [50]:
df3['name'].str.lower()

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [51]:
#add or Modify the columns or data if needed

In [52]:
gender = ['m', 'm','m', 'm', 'f', 'f', 'm', 'm', 'f', 'm']

In [54]:
df3['gender'] = gender

In [55]:
df3

   roll     name class  marks  age gender
0     1     anil    TE  56.77   22      m
1     2     amit    TE  59.77   21      m
2     3   aniket    BE  76.88   19      m
3     4  ajinkya    TE  69.66   20      m
4     5     asha    TE  63.28   20      f
5     6     Geet    BE  49.55   20      f
6     7     amar    BE  65.34   19      m
7     8    amita    BE  68.33   23      m
8     9     amol    TE  56.75   20      f
9    10    anmol    BE  78.66   21      m

In [56]:
df = df3

In [57]:
df

   roll     name class  marks  age gender
0     1     anil    TE  56.77   22      m
1     2     amit    TE  59.77   21      m
2     3   aniket    BE  76.88   19      m
3     4  ajinkya    TE  69.66   20      m
4     5     asha    TE  63.28   20      f
5     6     Geet    BE  49.55   20      f
6     7     amar    BE  65.34   19      m
7     8    amita    BE  68.33   23      m
8     9     amol    TE  56.75   20      f
9    10    anmol    BE  78.66   21      m

In [58]:
df['roll'] = df['roll'] + 100
df

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
5   106     Geet    BE  49.55   20      f
6   107     amar    BE  65.34   19      m
7   108    amita    BE  68.33   23      m
8   109     amol    TE  56.75   20      f
9   110    anmol    BE  78.66   21      m

In [59]:
df3

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      m
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
5   106     Geet    BE  49.55   20      f
6   107     amar    BE  65.34   19      m
7   108    amita    BE  68.33   23      m
8   109     amol    TE  56.75   20      f
9   110    anmol    BE  78.66   21      m

In [60]:
df['cgpa'] = df['marks']/10+1.5
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106     Geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      m  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [61]:
df.sort_values(by = 'name')

   roll     name class  marks  age gender   cgpa
5   106     Geet    BE  49.55   20      f  6.455
3   104  ajinkya    TE  69.66   20      m  8.466
6   107     amar    BE  65.34   19      m  8.034
1   102     amit    TE  59.77   21      m  7.477
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
2   103   aniket    BE  76.88   19      m  9.188
0   101     anil    TE  56.77   22      m  7.177
9   110    anmol    BE  78.66   21      m  9.366
4   105     asha    TE  63.28   20      f  7.828

In [62]:
df3.sort_values(by=['class', 'marks'])

   roll     name class  marks  age gender   cgpa
5   106     Geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      m  8.034
7   108    amita    BE  68.33   23      m  8.333
2   103   aniket    BE  76.88   19      m  9.188
9   110    anmol    BE  78.66   21      m  9.366
8   109     amol    TE  56.75   20      f  7.175
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
4   105     asha    TE  63.28   20      f  7.828
3   104  ajinkya    TE  69.66   20      m  8.466

In [63]:
df['marks'].mean()

np.float64(64.499)

In [64]:
df.describe()

            roll      marks        age       cgpa
count   10.00000  10.000000  10.000000  10.000000
mean   105.50000  64.499000  20.500000   7.949900
std      3.02765   9.207179   1.269296   0.920718
min    101.00000  49.550000  19.000000   6.455000
25%    103.25000  57.520000  20.000000   7.252000
50%    105.50000  64.310000  20.000000   7.931000
75%    107.75000  69.327500  21.000000   8.432750
max    110.00000  78.660000  23.000000   9.366000

In [65]:
# groupby

In [66]:
gr = df.groupby('class')
gr.groups

{'BE': [2, 5, 6, 7, 9], 'TE': [0, 1, 3, 4, 8]}

In [68]:
gr.get_group('BE')

   roll    name class  marks  age gender   cgpa
2   103  aniket    BE  76.88   19      m  9.188
5   106    Geet    BE  49.55   20      f  6.455
6   107    amar    BE  65.34   19      m  8.034
7   108   amita    BE  68.33   23      m  8.333
9   110   anmol    BE  78.66   21      m  9.366

In [69]:
gr.min()

       roll     name  marks  age gender   cgpa
class
BE      103     Geet  49.55   19      f  6.455
TE      101  ajinkya  56.75   20      f  7.175

In [70]:
gr['marks'].mean()

class
BE    67.752
TE    61.246
Name: marks, dtype: float64

In [72]:
#boolean filtering

In [73]:
df['marks'] > 60

0    False
1    False
2     True
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: marks, dtype: bool

In [74]:
df[df['marks'] > 60]

   roll     name class  marks  age gender   cgpa
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
6   107     amar    BE  65.34   19      m  8.034
7   108    amita    BE  68.33   23      m  8.333
9   110    anmol    BE  78.66   21      m  9.366

In [75]:
df[df['class'] == 'BE'[df['marks'] > 60]

_IncompleteInputError: incomplete input (2794260312.py, line 1)

In [76]:
df[(df['class'] == 'BE') & (df['marks'] > 60)]

   roll    name class  marks  age gender   cgpa
2   103  aniket    BE  76.88   19      m  9.188
6   107    amar    BE  65.34   19      m  8.034
7   108   amita    BE  68.33   23      m  8.333
9   110   anmol    BE  78.66   21      m  9.366

In [78]:
df.drop(1:)

SyntaxError: invalid syntax (791543154.py, line 1)

In [79]:
df.drop(columns=['name'])

   roll class  marks  age gender   cgpa
0   101    TE  56.77   22      m  7.177
1   102    TE  59.77   21      m  7.477
2   103    BE  76.88   19      m  9.188
3   104    TE  69.66   20      m  8.466
4   105    TE  63.28   20      f  7.828
5   106    BE  49.55   20      f  6.455
6   107    BE  65.34   19      m  8.034
7   108    BE  68.33   23      m  8.333
8   109    TE  56.75   20      f  7.175
9   110    BE  78.66   21      m  9.366

In [80]:
df.drop('name', axis=1)

   roll class  marks  age gender   cgpa
0   101    TE  56.77   22      m  7.177
1   102    TE  59.77   21      m  7.477
2   103    BE  76.88   19      m  9.188
3   104    TE  69.66   20      m  8.466
4   105    TE  63.28   20      f  7.828
5   106    BE  49.55   20      f  6.455
6   107    BE  65.34   19      m  8.034
7   108    BE  68.33   23      m  8.333
8   109    TE  56.75   20      f  7.175
9   110    BE  78.66   21      m  9.366

In [83]:
df.drop(columns=['name', 'class'])

   roll  marks  age gender   cgpa
0   101  56.77   22      m  7.177
1   102  59.77   21      m  7.477
2   103  76.88   19      m  9.188
3   104  69.66   20      m  8.466
4   105  63.28   20      f  7.828
5   106  49.55   20      f  6.455
6   107  65.34   19      m  8.034
7   108  68.33   23      m  8.333
8   109  56.75   20      f  7.175
9   110  78.66   21      m  9.366

In [84]:
df.drop(['gender', 'cgpa'], axis = 1, inplace = True)

In [85]:
df

   roll     name class  marks  age
0   101     anil    TE  56.77   22
1   102     amit    TE  59.77   21
2   103   aniket    BE  76.88   19
3   104  ajinkya    TE  69.66   20
4   105     asha    TE  63.28   20
5   106     Geet    BE  49.55   20
6   107     amar    BE  65.34   19
7   108    amita    BE  68.33   23
8   109     amol    TE  56.75   20
9   110    anmol    BE  78.66   21

In [87]:
newdf = pd.DataFrame({
    'roll': df['roll'],
    'gender': gender,
    'cgpa': df['marks']/10 + 1.5
})

In [88]:
newdf

   roll gender   cgpa
0   101      m  7.177
1   102      m  7.477
2   103      m  9.188
3   104      m  8.466
4   105      f  7.828
5   106      f  6.455
6   107      m  8.034
7   108      m  8.333
8   109      f  7.175
9   110      m  9.366

In [89]:
pd.merge(df, newdf)

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      m  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106     Geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      m  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [94]:
newdf = pd.read_csv('student5.csv')
newdf

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [95]:
pd.concat([df, newdf], ignore_index= True)

    roll     name class  marks  age
0    101     anil    TE  56.77   22
1    102     amit    TE  59.77   21
2    103   aniket    BE  76.88   19
3    104  ajinkya    TE  69.66   20
4    105     asha    TE  63.28   20
5    106     Geet    BE  49.55   20
6    107     amar    BE  65.34   19
7    108    amita    BE  68.33   23
8    109     amol    TE  56.75   20
9    110    anmol    BE  78.66   21
10     1   surbhi    TE  67.44   23
11     2    sujay    TE  74.12   22
12     3  subhash    BE  82.44   21
13     4   sachin    TE  59.33   21
14     5  shalini    TE  63.45   20

In [91]:
f = df[(df['marks'] > 60) & (df['class'] == 'BE')  ]

In [92]:
f.to_csv('op.csv', index = False)

In [93]:
f

   roll    name class  marks  age
2   103  aniket    BE  76.88   19
6   107    amar    BE  65.34   19
7   108   amita    BE  68.33   23
9   110   anmol    BE  78.66   21