In [1]:
import pandas as pd

In [2]:
roll = pd.Series([1,2,3,4,5])
name = pd.Series(['Sia', 'Ravi', 'Geet', 'Ajeenkya', 'Avinash'])
marks = pd.Series([85, 67, 59, 40, 90])

In [3]:
df = pd.DataFrame({
    'id': roll,
    'name': name,
    'marks': marks
})

In [4]:
df

   id      name  marks
0   1       Sia     85
1   2      Ravi     67
2   3      Geet     59
3   4  Ajeenkya     40
4   5   Avinash     90

In [6]:
df.ndim

2

In [7]:
df.shape

(5, 3)

In [9]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [10]:
df.size

15

In [11]:
pwd

'c:\\Users\\shrey\\Internship_learning\\Week4\\Day3'

In [12]:
df = pd.read_csv("student.csv")
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [13]:
df.shape

(10, 5)

In [14]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [15]:
df1 = pd.read_csv("student1.csv")
df1

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [22]:
col = ['roll', 'name', 'class', 'marks', 'age']

In [23]:
df1 = pd.read_csv('student1.csv', names = col)

In [24]:
df1

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [ ]:
df3 = pd.read_csv('student3.tsv', sep='\t')
df3

  roll\tname\tclass\tmarks\tage
0        1\tanil\tTE\t56.77\t22
1        2\tamit\tTE\t59.77\t21
2      3\taniket\tBE\t76.88\t19
3     4\tajinkya\tTE\t69.66\t20
4        5\tasha\tTE\t63.28\t20
5      6\tayesha\tBE\t49.55\t20
6        7\tamar\tBE\t65.34\t19
7       8\tamita\tBE\t68.33\t23
8        9\tamol\tTE\t56.75\t20
9      10\tanmol\tBE\t78.66\t21